### ISSUE TITLE
うまくできない遺伝子名がある

### ISSUE THREAD

**Issue by ryogam8** [iGEMTokyoTech/FASTASearchpy#1]
```
python FASTASearch.py -g 'CTLA4' -k 'human'                                                                                                                                      
The input genename is same with Official Symbol name
```
成功。

```
python FASTASearch.py -g 'PDL1' -k 'human'
Traceback (most recent call last):
  File "FASTASearch.py", line 112, in <module>
    ncbi_checker(ncbisoup, genename)
  File "FASTASearch.py", line 81, in ncbi_checker
    Egenename = str(ncbisoup.find('dl', id="summaryDl").find('dd', class_='noline')).replace('<', '>').split('>')[2]    
AttributeError: 'NoneType' object has no attribute 'find'
```
失敗。

**Comment by ryogam8** [comment]
おそらくデータの大きさによってエラーが出力されるかされないか決まりそう。

**Comment by ryogam8** [comment]
遺伝子ごとに検索時の結果画面が若干異なることが原因であった。
